### ISSUE TITLE
Sliding Window using objects as data

### ISSUE THREAD

**Issue by panickos** [darach/eep-js#9]
Hi,

In my application I'm using complex objects as data items to processed in windows and I have a custom function to accumulate and compensate. The sliding window uses a Buffer to store the values inside the window which make using objects impossible, since to compensate you need to have the evicting item.

I manually made a change to your code (lib/eep.window_sliding.js) to change the Buffer into an Array.

In this issue I'm just suggesting using the Array instead to make your implementation more generic. I know that this would somewhat increase the memory usage.

Here's what I changed:
var p = new Array(size);

Cheers,
Panickos

**Comment by darach** [comment]
Hi Panickos,

Thanks for the ping / note. I'll change to Array.

Cheers,

Darach.

**Comment by darach** [comment]
Hi Panickos,

Fixed and commited.

Cheers,

Darach.
